Use devcontainer
WealthWizardsEngineering/ww-code-test pull request #12
Opened 2021-04-28 13:31 UTC by j0nnylester

This adds a .devcontainer folder the code test can be completed in a VS Code devcontainer or using Github Codespaces in browser. I also took the time to update dependencies.

2021-04-28 13:51 UTC, rob1256 approved these changes

2021-04-29 07:18 UTC, mrwithersea requested changes
Great initiative on this @j0nnylester, really awesome improvement to add the option to run in vscode dev-containers and github codespaces, will make our test much more accessible 👏

2021-04-29 07:18 UTC, mrwithersea commented on README.md
> +More information about developing in a container can be found in the [VS Code documentation](https://code.visualstudio.com/docs/remote/containers#_quick-start-open-an-existing-folder-in-a-container)
Would be good to add a comment about using codespaces too now you've proved it 💪

2021-04-29 07:18 UTC, mrwithersea commented on package.json
>    "dependencies": {
Loads of updates, thank you @j0nnylester

2021-04-29 15:31 UTC, mrwithersea approved these changes

2021-04-29 15:34 UTC, merged